#include "nsISupports.idl"

[scriptable, uuid(c45fa464-7a67-485d-92b9-3d2fdf66cd3c)]

interface IMacOSKeychainItem : nsISupports {
    attribute AString accountName;
    attribute AString password;
    attribute AString protocol;
    attribute AString serverName;
    attribute unsigned short port;
    attribute AString securityDomain;
    attribute AString comment;
    attribute AString label;
    attribute AString description;
    attribute unsigned short authenticationType;
    
    void delete();
    
    const unsigned short AuthTypeDefault = 1;
    const unsigned short AuthTypeHTMLForm = 2;
    const unsigned short AuthTypeHTTPBasic = 3;
    
    /*attribute AString passwordField;
    void init(in AString aHostname,
              in AString aFormSubmitURL, in AString aHttpRealm,
              in AString aUsername,      in AString aPassword,
              in AString aUsernameField, in AString aPasswordField);
    boolean equals(in nsILoginInfo aLoginInfo);
    boolean matches(in nsILoginInfo aLoginInfo, in boolean ignorePassword);
    nsILoginInfo clone();*/
};
